### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by xieyuheng** [gnooth/feline#3]
```
  /home/xyh/lang/forth/imp/feline (master)
l
benchmarks/  COPYING  CREDITS  Makefile  src/

  /home/xyh/lang/forth/imp/feline (master)
make
cd src && make
make[1]: Entering directory '/home/xyh/lang/forth/imp/feline/src'
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o main.o main.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o os.o os.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o terminal.o terminal.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o backtrace.o backtrace.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o random.o random.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o numbers.o numbers.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o math.o math.c
clang --std=c99 -D_GNU_SOURCE -g -m64 -O1 -c -o socket.o socket.c
clang feline_home.c -o feline_home
./feline_home
echo "%define VERSION \"`git describe --tags`\"" > version.asm
nasm  -g -felf64 feline.asm
clang -m64 -lm main.o os.o terminal.o backtrace.o random.o numbers.o math.o socket.o feline.o -o ../feline
/usr/bin/ld: feline.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:60: ../feline] Error 1
make[1]: Leaving directory '/home/xyh/lang/forth/imp/feline/src'
make: *** [Makefile:10: FELINE_EXE] Error 2

  2  /home/xyh/lang/forth/imp/feline (master)
```

**Comment by gnooth** [comment]
Thanks for the report!

I've only tried building the latest version of Feline on the current version of Ubuntu (17.04), and that works with no problems.

What operating system and distribution are you using? And what version?

Thanks again!

-Peter

**Comment by gnooth** [comment]
What happens if you add -fPIC to the CFLAGS line in src/Makefile (line 26):

    CFLAGS = --std=c99 -D_GNU_SOURCE -g -m64 -fPIC

**Comment by xieyuheng** [comment]
I am using archlinux, here is the 
```
  /home/xyh/lang/forth/imp/feline/src (master)
cat /proc/version
Linux version 4.12.8-1-max98090 (dean@archlxc) (gcc version 7.1.1 20170630 (GCC) ) #1 SMP PREEMPT Thu Aug 17 09:34:54 UTC 2017

  /home/xyh/lang/forth/imp/feline/src (master)
uname -a
Linux cicada 4.12.8-1-max98090 #1 SMP PREEMPT Thu Aug 17 09:34:54 UTC 2017 x86_64 GNU/Linux
```

**Comment by xieyuheng** [comment]
I tried to add -fPIC to CFLAGS,
but 'feline.o' is compiled by nasm, 
maybe this issue is similar ? :: 
  https://stackoverflow.com/questions/22691370/nasm-issue-relocation-r-x86-64-pc32-shared-library

**Comment by gnooth** [comment]
Yes, that issue is similar, but the suggested fix won't work. The code in the .asm files is not intended to be relocatable. Changing to DEFAULT REL breaks things. In general, applications (as opposed to libraries) shouldn't need to be relocated, and the build works fine on Ubuntu (although it only works fine with clang; gcc has a problem on Ubuntu similar to your problem on archlinux).

Maybe I'll install archlinux...

**Comment by gnooth** [comment]
Try this:

In src/Makefile, change "CC = clang" to "CC = gcc" (line 23) and change "LINKFLAGS = -m64 -lm" to "LINKFLAGS = -lm -no-pie" (line 30) and do "make clean ; make". This works for me on Arch Linux with gcc 7.1.1 20170630, and the resulting executable passes all its tests (type "run-tests" at the repl prompt).

I haven't committed these changes yet because they break the build on Ubuntu (in a totally different way).

**Comment by xieyuheng** [comment]
great!
thanks for your work on this issue :)

feel free to close this issue when you wish to,
I can edit the makefile by my self when I need to build feline.

**Comment by xieyuheng** [comment]
by the way, I have some questions about closure if you are open to language design discussion.

**Comment by gnooth** [comment]
I am always open to language design discussion!

**Comment by gnooth** [comment]
I've checked in a fixed src/Makefile which works with both Ubuntu and Arch Linux (commit 8c5589f82fafc7329ca227c8217ba6be2f2a6468).

Thanks again for reporting the problem!

-Peter
